name: Build PDF in parallel (with log output)

on:
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        part: [hpmor-1, hpmor-2, hpmor-3, hpmor-4, hpmor-5, hpmor-6]
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 1 # 0 if you want to push to repo

      - name: cache LaTeX files
        uses: actions/cache@v4
        with:
          path: |
            chapters/*.aux
            hpmor*.aux
            hpmor*.fdb_latexmk
            hpmor*.fls
            hpmor*.out
            hpmor*.pdf
            hpmor*.toc
            hpmor*.xdv
          key: latex-build-files

      - name: install PDF requirements
        run: |
          # not: to save time
          # sudo apt update > /dev/null
          sh scripts/install_requirements_pdf.sh > /dev/null

      - name: make PDF
        run: latexmk ${{ matrix.part }} > /dev/null

      - name: publish PDF to release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: WorkInProgress
          prerelease: true
          files: ${{ matrix.part }}.pdf

      - name: upload log as artifact
        uses: actions/upload-artifact@v4
        with:
          name: "${{ matrix.part }}.log"
          path: "${{ matrix.part }}.log"
