name: Build PDF 1 selected
# no apt update included

on:
  workflow_dispatch:
    inputs:
      pdf_target:
        description: "Which PDF? (hpmor, hpmor-1, ..., hpmor-6)"
        required: true
        default: "hpmor"

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Print selection
        run: |
          echo "selected PDF: ${{ github.event.inputs.pdf_target }}"

      - name: Print start date
        run: date +%Y-%m-%d_%H:%M

      - name: Check out repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 1 # 0 if you want to push to repo

      - name: caching LaTeX files
        uses: actions/cache@v4
        with:
          path: |
            chapters/*.aux
            hpmor*.aux
            hpmor*.fdb_latexmk
            hpmor*.fls
            hpmor*.out
            hpmor*.pdf
            hpmor*.toc
            hpmor*.xdv
          key: latex-build-files

      - name: ls chapters
        run: ls -l chapters/

      - name: Python set up
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          # cache: "pip"

      - name: ls before
        run: |
          pwd
          ls -l

      - name: Check chapters for known issues
        run: python3 -O scripts/check_chapters.py

      - name: Install PDF requirements
        run: |
          # not: to save time
          # sudo apt-get update > /dev/null
          sh scripts/install_requirements_pdf.sh > /dev/null

      - name: Print versions
        run: |
          cat /etc/os-release
          xelatex -v
          latexmk -v
          # pandoc -v
          python3 --version

      - name: Make PDF
        run: |
          latexmk "${{ github.event.inputs.pdf_target }}" > /dev/null

      - name: Publish PDF to release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: WorkInProgress
          prerelease: true
          files: |
            ./hpmor*.pdf

      - name: Upload log as artifact
        uses: actions/upload-artifact@v4
        with:
          name: "${{ github.event.inputs.pdf_target }}.log"
          path: "${{ github.event.inputs.pdf_target }}.log"

      - name: ls after
        run: |
          ls -l

      - name: Print end date
        run: date +%Y-%m-%d_%H:%M
